"""add user display names and web port settings

Revision ID: 55dd08c6519c
Revises: 6fd146bfc946
Create Date: 2026-08-10 01:23:13.057031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55dd08c6519c'
down_revision = '6fd146bfc946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('web_scheme', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_column('web_scheme')
        batch_op.drop_column('display_name')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
