"""add connection interfaces

Revision ID: 7d2f4c1a9b3e
Revises: c71378a1e1c3
Create Date: 2026-08-15 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2f4c1a9b3e'
down_revision = 'c71378a1e1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_interface_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_interface_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_connections_source_interface_id',
            'interfaces',
            ['source_interface_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_connections_target_interface_id',
            'interfaces',
            ['target_interface_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_connections_target_interface_id', type_='foreignkey')
        batch_op.drop_constraint('fk_connections_source_interface_id', type_='foreignkey')
        batch_op.drop_column('target_interface_id')
        batch_op.drop_column('source_interface_id')
    # ### end Alembic commands ###