"""add device connections

Revision ID: c71378a1e1c3
Revises: 55dd08c6519c
Create Date: 2026-08-10 10:03:00.305043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71378a1e1c3'
down_revision = '55dd08c6519c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_device_id', sa.Integer(), nullable=False),
    sa.Column('target_device_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('source_port_id', sa.Integer(), nullable=True),
    sa.Column('target_port_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['source_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['target_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    # ### end Alembic commands ###
